# Generated by Django 4.2.3 on 2023-07-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depoimentos", "0002_depoimento_delete_depoimentos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depoimento",
            name="foto",
            field=models.ImageField(blank=True, upload_to="foto/depoimentos"),
        ),
    ]
