# Generated by Django 4.2.3 on 2023-07-31 20:32

import depoimentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depoimentos", "0003_alter_depoimento_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depoimento",
            name="foto",
            field=models.ImageField(
                blank=True, upload_to=depoimentos.models.declarador_directory_path
            ),
        ),
    ]
