# Generated by Django 4.2.3 on 2023-07-31 20:32

from django.db import migrations, models

import app.destinos.models


class Migration(migrations.Migration):

    dependencies = [
        ('destinos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='destino',
            name='preco',
        ),
        migrations.AddField(
            model_name='destino',
            name='foto_1',
            field=models.ImageField(
                blank=True, upload_to=app.destinos.models.destino_directory_path
            ),
        ),
        migrations.AddField(
            model_name='destino',
            name='foto_2',
            field=models.ImageField(
                blank=True, upload_to=app.destinos.models.destino_directory_path
            ),
        ),
        migrations.AddField(
            model_name='destino',
            name='meta_descricao',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='destino',
            name='texto_descritivo',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
