# Generated by Django 4.2.3 on 2023-07-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Depoimentos',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nome', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, upload_to='')),
                ('depoimento', models.CharField(max_length=100)),
            ],
        ),
    ]
